CourseWork/Controllers/AddVisitController.cs
using CourseWork.Models;
using CourseWork.Models.Contexts;
using CourseWork.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseWork.Controllers
{
    public class AddVisitController : Controller
    {
        private VetClinicDBContext db = new VetClinicDBContext();

        // GET: AddVisit
        public ActionResult Index()
        {
            return View(db.Employees./*Where(e => !string.IsNullOrEmpty(e.Speciality)).*/ToList());
        }

        [HttpPost]
        public ActionResult Index(int employeeID)
        {
            ViewBag.EmployeeID = employeeID;
            return View("ChooseHelper", db.Employees.Where(e => e.CanHelp && e.Id != employeeID).ToList());
        }

        [HttpPost]
        public ActionResult ChooseHelper(int employeeID, int helperID)
        {
            List<Employee> employess = db.Employees.Where(e => e.CanHelp).ToList();
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            return View("ChooseDate");
        }

        [HttpPost]
        public ActionResult ChooseDate(int employeeID, int helperID, DateTime date)
        {
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            ViewData["Date"] = date;
            List<Client> clients = db.Clients.ToList();
            return View("ChooseClient", clients);
        }

        [HttpPost]
        public ActionResult ChooseClient(int employeeID, int helperID, int clientID, DateTime date)
        {
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            ViewBag.ClientID = clientID;
            ViewData["Date"] = date;
            return View("ChooseAnimal");
        }

        [HttpPost]
        public ActionResult ChooseAnimal(int employeeID, int helperID, int clientID, DateTime date)
        {
            List<Animal> animals = db.Animals.Where(a => a.ClientId == clientID).ToList();
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            ViewBag.ClientID = clientID;
            ViewData["Date"] = date;
            return View("ChooseAnimal", animals);
        }

        [HttpPost]
        public ActionResult FillVisit(int employeeID, int helperID, int clientID, int animalID, DateTime date)
        {
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            ViewBag.ClientID = clientID;
            ViewBag.AnimalID = animalID;
            ViewData["Date"] = date;
            return View("FillVisit");
        }

        [HttpPost]
        public ActionResult ChooseProcedures(int employeeID, int helperID, int clientID, int animalID, string assignment, string diagnosis, DateTime date)
        {
            List<Procedure> procedures = db.Procedures.ToList();
            ViewBag.EmployeeID = employeeID;
            ViewBag.HelperID = helperID;
            ViewBag.ClientID = clientID;
            ViewBag.AnimalID = animalID;
            ViewData["Assignment"] = assignment;
            ViewData["Diagnosis"] = diagnosis;
            ViewData["Date"] = date;
            return View("ChooseProcedures", procedures);
        }

        [HttpPost]
        public ActionResult Confirm(int employeeID, int helperID, int clientID, int animalID, string assignment, string diagnosis, DateTime date, ProceduresCheckViewModel[] proceduresChecked)
        {
            int[] ids = proceduresChecked.Where(p=>p.Check).Select(p => p.ProcedureID).ToArray();
            Procedure[] procedures = db.Procedures.Where(p => ids.Contains(p.Id)).ToArray();
            float totalCost = 0;
            foreach (var item in procedures)
            {
                totalCost += item.Cost;
            }

            Visit visit = new Visit(animalID, employeeID, helperID, clientID, date, diagnosis, assignment, totalCost);
            visit.Procedures = procedures;
            db.Entry(visit).State = EntityState.Added;
            db.SaveChanges();
            return RedirectToAction("Index", "Visits");
        }
    }
}

CourseWork/Views/AddVisit/ChooseAnimal.cshtml
@model IEnumerable<CourseWork.Models.Animal>

@{
    ViewBag.Title = "ChooseAnimal";
}

<h2>Добавление приёма: Выберите питомца</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Breed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Type)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Breed)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BirthDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Photo)
    </td>
    <td>
        @using (Html.BeginForm("FillVisit", "AddVisit", FormMethod.Post))
        {
            @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
            @Html.Hidden("HelperID", ViewBag.HelperID as string)
            @Html.Hidden("ClientID", ViewBag.ClientID as string)
            @Html.Hidden("Date", ViewData["Date"] as string)
            <div>
                @Html.Hidden("AnimalID", item.Id)
                <input type="submit" value="Выбрать" class="btn btn-primary" />
            </div>
        }
    </td>
</tr>
}

</table>

CourseWork/Views/AddVisit/ChooseClient.cshtml
@model IEnumerable<CourseWork.Models.Client>

@{
    ViewBag.Title = "ChooseClient";
}

<h2>Добавление приёма: Выберите клиента</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @using (Html.BeginForm("ChooseAnimal", "AddVisit", FormMethod.Post))
                {
                    @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
                    @Html.Hidden("HelperID", ViewBag.HelperID as string)
                    @Html.Hidden("Date", ViewData["Date"])
                    <div>
                        @Html.Hidden("ClientID", item.Id)
                        <input type="submit" value="Выбрать" class="btn btn-primary" />
                    </div>
                }
            </td>
        </tr>
    }

</table>

CourseWork/Views/AddVisit/ChooseDate.cshtml
@{
    ViewBag.Title = "ChooseDate";
}

<h2>Добавление приёма: Выбор даты</h2>


@using (Html.BeginForm("ChooseDate", "AddVisit", FormMethod.Post))
{
    @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
    @Html.Hidden("HelperID", ViewBag.HelperID as string)
    @Html.Label("Выберите дату приёма");
    <input type="datetime-local" name="Date" class="form-control">
    <input type="submit" value="Выбрать" class="btn btn-primary">
}

CourseWork/Views/AddVisit/ChooseHelper.cshtml
@model IEnumerable<CourseWork.Models.Employee>

@{
    ViewBag.Title = "Выберите помощника";
}

<h2>Добавление приёма: Выберите помощника</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Post)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Post)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speciality)
            </td>
            <td>
                @using (Html.BeginForm("ChooseHelper", "AddVisit", FormMethod.Post))
                {
                    @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
                    <div>
                        @Html.Hidden("HelperID", item.Id)
                        <input type="submit" value="Выбрать" class="btn btn-primary" />
                    </div>
                }
            </td>
        </tr>
    }

</table>

CourseWork/Views/AddVisit/ChooseProcedures.cshtml
@model IEnumerable<CourseWork.Models.Procedure>

@{
    ViewBag.Title = "ChooseProcedures";
}


<h2>Добавление приёма: Выберите процедуры</h2>
@using (Html.BeginForm("Confirm", "AddVisit", FormMethod.Post))
{

    @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
    @Html.Hidden("HelperID", ViewBag.HelperID as string)
    @Html.Hidden("ClientID", ViewBag.ClientID as string)
    @Html.Hidden("AnimalID", ViewBag.AnimalID as string)
    @Html.Hidden("Assignment", ViewData["Assignment"] as string)
    @Html.Hidden("Diagnosis", ViewData["Diagnosis"] as string)
    @Html.Hidden("Date", ViewData["Date"] as string)
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @{
            int i = 0;
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                    @Html.Hidden($"proceduresChecked[{i}].ProcedureID", item.Id)
                </td>
                <td>
                    @Html.CheckBox($"proceduresChecked[{i}].Check", false, new { @class = "form-check-input" })
                </td>
            </tr>
            i++;
        }

    </table>
    <div class="form-group">
        <input type="submit" Value="Выбрать" class="btn btn-primary" />
    </div>
}

CourseWork/Views/AddVisit/FillVisit.cshtml
@model CourseWork.Models.Visit

@{
    ViewBag.Title = "FillVisit";
}

<h2>Добавление приёма: Заполните диагноз и назначение</h2>


@using (Html.BeginForm("ChooseProcedures", "AddVisit", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.Hidden("EmployeeID", ViewBag.EmployeeID as string)
    @Html.Hidden("HelperID", ViewBag.HelperID as string)
    @Html.Hidden("ClientID", ViewBag.ClientID as string)
    @Html.Hidden("AnimalID", ViewBag.AnimalID as string)
    @Html.Hidden("Date", ViewData["Date"] as string)
    <div class="form-group">
        @Html.LabelFor(model => model.Diagnosis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Diagnosis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Diagnosis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Assignment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Assignment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Assignment, "", new { @class = "text-danger" })
        </div>
    </div>
    <input type="submit" value="Далее" class="btn btn-primary">
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CourseWork/Views/AddVisit/Index.cshtml
@model IEnumerable<CourseWork.Models.Employee>

@{
    ViewBag.Title = "Добавление приёма";
}

<h2>Добавление приёма: Выберите специалиста</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Post)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CanHelp)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Post)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Speciality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CanHelp)
        </td>
        <td>
            @using (Html.BeginForm())
            {
                <div>
                    @Html.Hidden("EmployeeID", item.Id)
                    <input type="submit" value="Выбрать" class="btn btn-primary" />
                </div>
            }
        </td>
    </tr>
}

</table>